# Generated by Django 4.0.4 on 2022-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('reminder_hours', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '4'), (4, '24'), (5, '168')], null=True)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('start_date', 'start_time'),
            },
        ),
    ]
