# Generated by Django 4.0.4 on 2022-05-20 12:54


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('reminder_hours',
                 models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '4'), (4, '24'), (5, '168')],
                                     null=True)),
                ('is_holiday', models.BooleanField(default=False)),

                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),

            ],
            options={
                'ordering': ('start_date', 'start_time'),
            },
        ),
    ]
