# Generated by Django 4.0.4 on 2022-05-23 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='카테고리 없음', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Scheduletemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='템플릿', max_length=20, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('hp', '체력'), ('int', '지력'), ('will', '근성'), ('exp', '경험'), ('money', '재력'), ('ten', '행복')], default='will', max_length=8)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '스케쥴 템플릿',
                'verbose_name_plural': '스케쥴 템플릿 스케쥴 템플릿 목록',
                'db_table': 'Scheduletemplate',
            },
        ),
    ]
