# Generated by Django 4.0.4 on 2022-05-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduletemplates', '0002_alter_scheduletemplate_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='status',
            field=models.CharField(choices=[('hp', '체력'), ('int', '지력'), ('will', '근성'), ('exp', '경험'), ('money', '재력'), ('ten', '행복')], default='will', max_length=8),
        ),
    ]
