# Generated by Django 4.0.4 on 2022-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='total_schedules',
            field=models.IntegerField(default=0),
        ),
    ]
