# Generated by Django 4.0.4 on 2022-05-21 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_schedule_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='카테고리 없음', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='schedules.category'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='schedules.status'),
        ),
    ]
