# Generated by Django 4.0.4 on 2022-05-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedule_status_percent_schedule_total_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='status_percent',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='total_percent',
        ),
    ]
